import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, ChevronDown, RefreshCw, ShieldAlert } from 'lucide-react';
import { sheetVariantReconciliationApi, type ReconciliationCandidate, type SuggestedVariant, SheetVariantReconciliationApiError } from '../../../services/sheetVariantReconciliationApi';
import './SheetVariantReconciliation.css';
import { useAdminToast } from '../../../hooks/useAdminToast';

export const SheetVariantReconciliation = () => {
  const [items, setItems] = useState<ReconciliationCandidate[]>([]); const [selected, setSelected] = useState<ReconciliationCandidate | null>(null); const [suggestions, setSuggestions] = useState<SuggestedVariant[]>([]); const [busy, setBusy] = useState(false); const toast = useAdminToast();
  const load = useCallback(async () => { setBusy(true); try { const result = await sheetVariantReconciliationApi.unmatched(); setItems(result.items); } catch (error) { toast.error(error instanceof SheetVariantReconciliationApiError ? error.message : 'Unable to load reconciliation candidates.'); } finally { setBusy(false); } }, [toast]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const inspect = async (item: ReconciliationCandidate) => { setSelected(item); setBusy(true); try { const result = await sheetVariantReconciliationApi.candidates(item.candidateId); setSuggestions(result.canonicalCandidates); if (result.conflicts.length) toast.warning(result.conflicts.map((conflict) => conflict.reason).join(', ')); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to load candidate suggestions.'); } finally { setBusy(false); } };
  const confirm = async (variant: SuggestedVariant) => { if (!selected || !selected.medium || !selected.sheetSku || variant.warnings.length) return; setBusy(true); try { await sheetVariantReconciliationApi.createAlias({ namespace: selected.medium === 'physical_sim' ? 'SIM_HICO_SKU_PHYSICAL' : 'SIM_HICO_SKU_ESIM', externalKey: selected.sheetSku, medium: selected.medium, variantId: variant.variant.id }); toast.success('Mapping saved. Run a new preview to verify the matched count.'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to save mapping.'); } finally { setBusy(false); } };
  return <section className="sheet-variant-reconciliation"><header><div><h2>Sheet variant identity</h2><p>Review unmatched Sheet SKUs and confirm one canonical variant at a time.</p></div><button className="admin-btn-secondary" type="button" onClick={() => void load()} disabled={busy}><RefreshCw size={16} /> Refresh</button></header><div className="sheet-reconciliation-layout"><div className="sheet-reconciliation-table-wrap"><table><thead><tr><th>Row</th><th>Medium</th><th>Sheet SKU</th><th>WMID</th><th>Price</th><th>Duration</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.candidateId} className={selected?.candidateId === item.candidateId ? 'is-selected' : ''}><td>{item.sheetRowNumber}</td><td>{item.medium ?? '-'}</td><td>{item.sheetSku ?? '-'}</td><td>{item.wmproductId ?? '-'}</td><td>{item.price ?? '-'}</td><td>{item.durationDays ?? '-'}</td><td><button className="icon-text-button" type="button" onClick={() => void inspect(item)} disabled={busy}><ChevronDown size={15} /> Inspect</button></td></tr>)}</tbody></table>{items.length === 0 && <p className="sheet-reconciliation-empty">No unmatched candidates in the latest bounded preview.</p>}</div>{selected && <aside className="sheet-reconciliation-detail"><h3>Candidate row {selected.sheetRowNumber}</h3><dl><dt>SKU</dt><dd>{selected.sheetSku}</dd><dt>Medium</dt><dd>{selected.medium}</dd><dt>Provider identifier</dt><dd>{selected.wmproductId ?? 'None'}</dd></dl><h4>Suggested canonical variants</h4>{suggestions.map((suggestion) => <div className="sheet-reconciliation-suggestion" key={suggestion.variant.id}><strong>{suggestion.product?.name ?? suggestion.product?.slug ?? 'Unknown product'}</strong><span>{suggestion.variant.id} · {suggestion.variant.sku} · {suggestion.variant.medium}</span><small>{suggestion.evidence.map((evidence) => evidence.type).join(', ') || 'No direct evidence'}</small><button className="admin-btn-primary" type="button" disabled={busy || suggestion.warnings.length > 0} onClick={() => void confirm(suggestion)}><CheckCircle2 size={15} /> Confirm mapping</button>{suggestion.warnings.length > 0 && <small className="warning"><ShieldAlert size={14} /> {suggestion.warnings.map((warning) => warning.reason).join(', ')}</small>}</div>)}</aside>}</div></section>;
};
