import { useMemo, useState } from 'react';
import { Check, RefreshCw, X } from 'lucide-react';
import { CatalogSheetSyncApiError, catalogSheetSyncApi } from '../../../services/catalogSheetSyncApi';
import type { CatalogSheetSyncBatch, CatalogSheetSyncField, CatalogSheetSyncRow } from '../../../types/catalogSheetSync';
import './CatalogSheetSync.css';

const fields: Array<{ id: CatalogSheetSyncField; label: string }> = [{ id: 'price', label: 'Giá bán' }, { id: 'wmproductId', label: 'WM product ID' }, { id: 'apn', label: 'APN' }, { id: 'networkLabel', label: 'Mạng' }, { id: 'publicNote', label: 'Ghi chú public' }];
const displayError = (error: unknown, fallback: string) => error instanceof CatalogSheetSyncApiError && error.code === 'SHEET_SYNC_NOT_CONFIGURED' ? 'Chưa cấu hình Google Sheet.' : error instanceof Error ? error.message : fallback;
export const CatalogSheetSync = () => {
  const [batch, setBatch] = useState<CatalogSheetSyncBatch | null>(null); const [rows, setRows] = useState<CatalogSheetSyncRow[]>([]); const [selectedRows, setSelectedRows] = useState<string[]>([]); const [selectedFields, setSelectedFields] = useState<CatalogSheetSyncField[]>(fields.map((field) => field.id)); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const validRows = useMemo(() => rows.filter((row) => row.status === 'VALID'), [rows]);
  const preview = async () => { setBusy(true); setMessage(null); try { const result = await catalogSheetSyncApi.preview(); setBatch(result.batch); setRows(result.rows); setSelectedRows(result.rows.filter((row) => row.status === 'VALID').map((row) => row.id)); } catch (error) { setMessage(displayError(error, 'Không thể đọc Sheet.')); } finally { setBusy(false); } };
  const apply = async () => { if (!batch || !selectedRows.length) return; setBusy(true); setMessage(null); try { const result = await catalogSheetSyncApi.apply(batch.id, { rowIds: selectedRows, fields: selectedFields }); setBatch(result.batch); setRows(result.rows); } catch (error) { setMessage(error instanceof Error ? error.message : 'Không thể áp dụng thay đổi.'); } finally { setBusy(false); } };
  const reject = async () => { if (!batch) return; setBusy(true); try { const result = await catalogSheetSyncApi.reject(batch.id); setBatch(result.batch); } catch (error) { setMessage(error instanceof Error ? error.message : 'Không thể từ chối batch.'); } finally { setBusy(false); } };
  return <section className="sheet-sync-page"><header className="sheet-sync-header"><div><h2>Đồng bộ Google Sheet</h2><p>Chỉ đọc Sheet, xem trước thay đổi theo variant rồi phê duyệt thủ công.</p></div><button className="admin-btn-primary" type="button" onClick={preview} disabled={busy}><RefreshCw size={16} /> Đọc Sheet</button></header>{message && <p className="sheet-sync-message" role="alert">{message}</p>}{batch && <><div className="sheet-sync-summary"><span>Batch: {batch.id}</span><span>{batch.summary.valid ?? 0} hợp lệ</span><span>{batch.summary.invalid ?? 0} cần xử lý</span><span>Trạng thái: {batch.status}</span></div><div className="sheet-sync-controls"><label><input type="checkbox" checked={selectedRows.length === validRows.length && validRows.length > 0} onChange={(event) => setSelectedRows(event.target.checked ? validRows.map((row) => row.id) : [])} /> Chọn tất cả hợp lệ</label>{fields.map((field) => <label key={field.id}><input type="checkbox" checked={selectedFields.includes(field.id)} onChange={() => setSelectedFields((current) => current.includes(field.id) ? current.filter((id) => id !== field.id) : [...current, field.id])} /> {field.label}</label>)}</div><div className="sheet-sync-table-wrap"><table className="sheet-sync-table"><thead><tr><th></th><th>Dòng</th><th>Variant</th><th>Thay đổi</th><th>Trạng thái</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><input type="checkbox" disabled={row.status !== 'VALID'} checked={selectedRows.includes(row.id)} onChange={() => setSelectedRows((current) => current.includes(row.id) ? current.filter((id) => id !== row.id) : [...current, row.id])} /></td><td>{row.sheetRowNumber}</td><td>{row.variantId ?? 'Không khớp'}</td><td>{Object.entries(row.diff).filter(([, change]) => change?.changed).map(([field, change]) => <div key={field}>{field}: {String(change?.before ?? 'trống')} → {String(change?.after ?? 'trống')}</div>)}</td><td>{row.status === 'INVALID' ? <><X size={14} /> {row.errors.map((error) => error.code).join(', ')}</> : <><Check size={14} /> {row.status}</>}</td></tr>)}</tbody></table></div>{batch.status === 'READY_FOR_REVIEW' && <div className="sheet-sync-actions"><button className="admin-btn-secondary" type="button" onClick={reject} disabled={busy}>Từ chối batch</button><button className="admin-btn-primary" type="button" onClick={apply} disabled={busy || selectedRows.length === 0 || selectedFields.length === 0}>Áp dụng các trường đã chọn</button></div>}</>}</section>;
};
