import { Link } from 'react-router-dom';
import { LifeBuoy, Plus } from 'lucide-react';
import { SeoHead } from '../../seo/SeoHead';
import { defaultMetadata } from '../../seo/buildMetadata';
import { useCustomerTickets } from '../../hooks/customer/useCustomerTickets';
import { AccountErrorState } from '../../components/Account/AccountErrorState';
import { AccountLoadingState } from '../../components/Account/AccountLoadingState';
export const AccountSupportPage = () => { const { data, error, loading, reload, create } = useCustomerTickets(); const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await create({ subject: form.get('subject'), category: form.get('category'), priority: 'NORMAL', body: form.get('body') }); event.currentTarget.reset(); }; return <><SeoHead path="/tai-khoan/ho-tro" metadata={{ ...defaultMetadata(), title: 'Ho tro | HICO eSIM', indexable: false }} noindex /><div className="account-page-heading"><div><p className="account-kicker">Ho tro</p><h2>Yeu cau ho tro</h2><p className="account-lead">Gui yeu cau va theo doi trao doi voi HICO.</p></div></div><div className="account-detail-grid"><form className="account-panel account-form" onSubmit={(event) => void submit(event)}><h3><Plus size={18} /> Tao yeu cau</h3><label>Chu de<input name="subject" maxLength={160} required /></label><label>Danh muc<select name="category" defaultValue="ACCOUNT"><option value="ACCOUNT">Tai khoan</option><option value="ORDER">Don hang</option><option value="ASSET">Tai san</option><option value="TECHNICAL">Ky thuat</option><option value="OTHER">Khac</option></select></label><label>Noi dung<textarea name="body" rows={6} maxLength={5000} required /></label><button className="account-button account-button-primary" type="submit"><LifeBuoy size={16} /> Gui yeu cau</button></form><section className="account-panel"><h3>Lich su yeu cau</h3>{loading ? <AccountLoadingState /> : error ? <AccountErrorState onRetry={() => void reload()} /> : data?.items.length ? <div className="account-address-list">{data.items.map((ticket) => <Link className="account-address-row" to={`/tai-khoan/ho-tro/${ticket.id}`} key={ticket.id}><div><strong>{ticket.subject}</strong><span>{ticket.category} · {ticket.status}</span></div><span>{new Date(ticket.updatedAt).toLocaleDateString()}</span></Link>)}</div> : <p className="account-empty-state"><LifeBuoy size={26} />Chua co yeu cau ho tro.</p>}</section></div></>;
};
