import { useState } from 'react';
import { MapPin, Plus, Star, Trash2 } from 'lucide-react';
import { SeoHead } from '../../seo/SeoHead';
import { defaultMetadata } from '../../seo/buildMetadata';
import { useCustomerAddresses } from '../../hooks/customer/useCustomerAddresses';
import { AccountErrorState } from '../../components/Account/AccountErrorState';
import { AccountLoadingState } from '../../components/Account/AccountLoadingState';
export const AccountAddressesPage = () => { const { data, error, loading, create, setDefault, remove, reload } = useCustomerAddresses(); const [form, setForm] = useState({ recipientName: '', phone: '', addressLine1: '', district: '', city: '', isDefault: true }); const [message, setMessage] = useState(''); const update = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value })); const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await create(form); setForm({ recipientName: '', phone: '', addressLine1: '', district: '', city: '', isDefault: false }); setMessage('Địa chỉ đã được thêm.'); } catch (value) { setMessage(value instanceof Error ? value.message : 'Không thể lưu địa chỉ.'); } }; return <><SeoHead path="/tai-khoan/dia-chi" metadata={{ ...defaultMetadata(), title: 'Địa chỉ | HICO eSIM', indexable: false }} noindex /><div className="account-page-heading"><div><p className="account-kicker">Địa chỉ</p><h2>Địa chỉ giao hàng</h2><p className="account-lead">Địa chỉ được lưu theo tài khoản của bạn.</p></div></div>{message && <p className="account-feedback" role="status">{message}</p>}<div className="account-detail-grid"><form className="account-panel account-form" onSubmit={submit}><h3><Plus size={18} /> Thêm địa chỉ</h3>{[['recipientName','Người nhận'],['phone','Điện thoại'],['addressLine1','Địa chỉ'],['district','Quận/Huyện'],['city','Tỉnh/Thành']].map(([key, label]) => <label key={key}>{label}<input value={String(form[key as keyof typeof form] ?? '')} onChange={(event) => update(key, event.target.value)} required={['recipientName','addressLine1','city'].includes(key)} /></label>)}<label className="account-checkbox"><input type="checkbox" checked={form.isDefault} onChange={(event) => update('isDefault', event.target.checked)} /> Đặt làm mặc định</label><button className="account-button account-button-primary" type="submit"><MapPin size={16} /> Lưu địa chỉ</button></form><section className="account-panel"><h3>Danh sách địa chỉ</h3>{loading ? <AccountLoadingState /> : error ? <AccountErrorState onRetry={() => void reload()} /> : data.length ? <div className="account-address-list">{data.map((address) => <article className="account-address-row" key={address.id}><div><strong>{address.recipientName}</strong><span>{address.addressLine1}, {address.district ?? ''}, {address.city}</span><span>{address.phone ?? ''}</span></div><div className="account-row-actions">{address.isDefault ? <span className="account-status-good"><Star size={14} /> Mặc định</span> : <button className="account-icon-button" title="Đặt làm mặc định" aria-label="Đặt làm mặc định" onClick={() => void setDefault(address.id)}><Star size={16} /></button>}<button className="account-icon-button" title="Xóa địa chỉ" aria-label="Xóa địa chỉ" onClick={() => void remove(address.id)}><Trash2 size={16} /></button></div></article>)}</div> : <p className="account-muted">Chưa có địa chỉ.</p>}</section></div></>;
};
