import { useState } from 'react';
import { MapPin, Plus, Star, Trash2 } from 'lucide-react';
import { SeoHead } from '../../seo/SeoHead';
import { defaultMetadata } from '../../seo/buildMetadata';
import { useCustomerAddresses } from '../../hooks/customer/useCustomerAddresses';
import { AccountErrorState } from '../../components/Account/AccountErrorState';
import { AccountLoadingState } from '../../components/Account/AccountLoadingState';
export const AccountAddressesPage = () => { const { data, error, loading, create, setDefault, remove, reload } = useCustomerAddresses(); const [form, setForm] = useState({ recipientName: '', phone: '', addressLine1: '', district: '', city: '', isDefault: true }); const [message, setMessage] = useState(''); const update = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value })); const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await create(form); setForm({ recipientName: '', phone: '', addressLine1: '', district: '', city: '', isDefault: false }); setMessage('Dia chi da duoc them.'); } catch (value) { setMessage(value instanceof Error ? value.message : 'Khong the luu dia chi.'); } }; return <><SeoHead path="/tai-khoan/dia-chi" metadata={{ ...defaultMetadata(), title: 'Dia chi | HICO eSIM', indexable: false }} noindex /><div className="account-page-heading"><div><p className="account-kicker">Dia chi</p><h2>Dia chi giao hang</h2><p className="account-lead">Dia chi duoc luu theo tai khoan cua ban.</p></div></div>{message && <p className="account-feedback" role="status">{message}</p>}<div className="account-detail-grid"><form className="account-panel account-form" onSubmit={submit}><h3><Plus size={18} /> Them dia chi</h3>{[['recipientName','Nguoi nhan'],['phone','Dien thoai'],['addressLine1','Dia chi'],['district','Quan/Huyen'],['city','Tinh/Thanh']].map(([key, label]) => <label key={key}>{label}<input value={String(form[key as keyof typeof form] ?? '')} onChange={(event) => update(key, event.target.value)} required={['recipientName','addressLine1','city'].includes(key)} /></label>)}<label className="account-checkbox"><input type="checkbox" checked={form.isDefault} onChange={(event) => update('isDefault', event.target.checked)} /> Dat lam mac dinh</label><button className="account-button account-button-primary" type="submit"><MapPin size={16} /> Luu dia chi</button></form><section className="account-panel"><h3>Danh sach dia chi</h3>{loading ? <AccountLoadingState /> : error ? <AccountErrorState onRetry={() => void reload()} /> : data.length ? <div className="account-address-list">{data.map((address) => <article className="account-address-row" key={address.id}><div><strong>{address.recipientName}</strong><span>{address.addressLine1}, {address.district ?? ''}, {address.city}</span><span>{address.phone ?? ''}</span></div><div className="account-row-actions">{address.isDefault ? <span className="account-status-good"><Star size={14} /> Mac dinh</span> : <button className="account-icon-button" title="Dat lam mac dinh" aria-label="Dat lam mac dinh" onClick={() => void setDefault(address.id)}><Star size={16} /></button>}<button className="account-icon-button" title="Xoa dia chi" aria-label="Xoa dia chi" onClick={() => void remove(address.id)}><Trash2 size={16} /></button></div></article>)}</div> : <p className="account-muted">Chua co dia chi.</p>}</section></div></>;
};
